export const GET_PASTE_FROM_URL = "GET_PASTE_FROM_URL";
export const CLEAR_PASTE = "CLEAR_PASTE";
export const DECRYPT_PASTE = "DECRYPT_PASTE";
export const SET_DECRYPTED_PASTE = "SET_DECRYPTED_PASTE";

export const READ_SETTINGS = "READ_SETTINGS";
export const SET_SETTINGS = "SET_SETTINGS";
export const LOAD_THEME = "LOAD_THEME";
export const SET_THEME = "SET_THEME";

export const SET_HIGHLIGHTED_LINES = "SET_HIGHLIGHTED_LINES";
export const ADD_HIGHLIGHTED_LINE = "ADD_HIGHLIGHTED_LINE";
export const ADD_HIGHLIGHTED_LINES = "ADD_HIGHLIGHTED_LINES";
